### ISSUE TITLE
Needs 100% more TLS

### ISSUE THREAD

**Issue by alatalo** [badrap/badrap.github.io#4]
Our main web site has invalid certification.

EDIT: removed the https-url pointing to the site, to avoid it being indexed/scored. -evilon

**Comment by evilon** [comment]
The issue actually is that we don't use https right now. Github pages + custom domains  = no proper https-support. The fact that there is something there is an undesired side-effect. We should not share the https-link before we have proper https-site available.

**Comment by nkapu** [comment]
https-site is now available and all traffic is currently being redirected to https.
